#!/bin/bash
#pare feu : port 22 en tcp
ufw enable
ufw allow 22
ufw allow 22/tcp
#install serveur ssh et edition de la config
apt install -y openssh-server
rm /etc/ssh/sshd_config
touch /etc/ssh/sshd_config
echo "
Port 22
PermitRootLogin yes
PasswordAuthentication yes
PermitEmptyPasswords no
ChallengeResponseAuthentication no
UsePAM yes
AcceptEnv LANG LC_*" >> /etc/ssh/sshd_config
touch /root/flag.txt
echo "-4251626237309116968" >> /root/flag.txt
echo "ubuntu:RHq!5EPFiRHq!5EPFi" | chpasswd
echo "root:azerty$" | chpasswd
service sshd restart
rm -rf ydaysb3_orga
chattr -R +i /root
chattr -R +i /boot
chattr -R +i /home
mv /usr/bin/chattr /usr/bin/chm0d